/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import users.deleteUser;
import users.loginViewUser;
import users.updateUser;
import users.registerUser;
import finance.reviewChurchDonations;
import finance.search_Donations;
import finance.add_Donation;
import Forms.admin.deleteMember;
import Forms.admin.updateMember;
import Forms.admin.showAllData;
import Forms.admin.searchMember;
import Forms.admin.addMembers;
import static Forms.login.access;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahryar Khan
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    addMembers ad;
    public MainPage() {
        initComponents();
        
        if(access.equals("Super Admin"))
        {
           // btnAdd2.setEnabled(false);
        }else  if(access.equals("Admin"))
        {
            btn_addo.setEnabled(false);
            btn_viewAllo.setEnabled(false);
            btn_searcho.setEnabled(false);
            btn_viewAllReg.setEnabled(false);
            btn_newReg.setEnabled(false);
            btn_removeReg.setEnabled(false);
            btn_updateReg.setEnabled(false);
            
            
        }else  if(access.equals("Finance")){
            
             btn_addRecord.setEnabled(false);
             btn_updateRecord.setEnabled(false);
             btn_searchRecord.setEnabled(false);
             btn_deleteRecord.setEnabled(false);
             btn_viewAllRecord.setEnabled(false);
             btn_viewAllReg.setEnabled(false);
            btn_newReg.setEnabled(false);
            btn_removeReg.setEnabled(false);
            btn_updateReg.setEnabled(false);
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btn_deleteRecord = new javax.swing.JButton();
        btn_updateRecord = new javax.swing.JButton();
        btn_searchRecord = new javax.swing.JButton();
        btn_addRecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_viewAllRecord = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_viewAllo = new javax.swing.JButton();
        btn_addo = new javax.swing.JButton();
        btn_searcho = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_newReg = new javax.swing.JButton();
        btn_removeReg = new javax.swing.JButton();
        btn_updateReg = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        btn_viewAllReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Christ Church Members Management Software- v1.0");

        btn_deleteRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_deleteRecord.setText("DELETE RECORD");
        btn_deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteRecordActionPerformed(evt);
            }
        });

        btn_updateRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_updateRecord.setText("UPDATE RECORD");
        btn_updateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateRecordActionPerformed(evt);
            }
        });

        btn_searchRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_searchRecord.setText("SEARCH RECORD");
        btn_searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchRecordActionPerformed(evt);
            }
        });

        btn_addRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_addRecord.setText("ADD RECORD");
        btn_addRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addRecordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CHRIST CHURCH MEMBERS  MANAGEMENT SOFTWEAR");

        btn_viewAllRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_viewAllRecord.setText("VIEW ALL RECORDS");
        btn_viewAllRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewAllRecordActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CHURCH MEMBERS MANAGEMENT");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CHURCH OFFERTORY MANAGEMENT");
        jLabel7.setOpaque(true);

        btn_viewAllo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_viewAllo.setText("REVIEW ALL OFFERTORISE");
        btn_viewAllo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewAlloActionPerformed(evt);
            }
        });

        btn_addo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_addo.setText("ADD MEMBER'S OFFERTORY");
        btn_addo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addoActionPerformed(evt);
            }
        });

        btn_searcho.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_searcho.setText("SEARCH MEMBER'S OFFERTORY");
        btn_searcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchoActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SOFTWARE USER MANAGEMENT");
        jLabel8.setOpaque(true);

        btn_newReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_newReg.setText("REGISTER NEW USER");
        btn_newReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newRegActionPerformed(evt);
            }
        });

        btn_removeReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_removeReg.setText("REMOVE EXISTING USER");
        btn_removeReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeRegActionPerformed(evt);
            }
        });

        btn_updateReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_updateReg.setText("UPDATE USER CREDENTIALS");
        btn_updateReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateRegActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Exit");
        jLabel9.setOpaque(true);

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton15.setText("EXIT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        btn_viewAllReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_viewAllReg.setText("VIEW ALL USERS");
        btn_viewAllReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewAllRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_searcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_viewAllo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(btn_addo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_viewAllRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_searchRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_deleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_updateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_updateReg, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(btn_newReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_removeReg, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_viewAllReg, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_viewAllRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_searchRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_deleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_viewAllo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_searcho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_newReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removeReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_viewAllReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteRecordActionPerformed
        
     //  this.setVisible(false);  
     deleteMember d=new deleteMember();
     d.setVisible(true); 
     //d.setExtendedState(JFrame.MAXIMIZED_BOTH);
      d.setSize(700, 600);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        d.setLocation(dim.width/2-d.getSize().width/2, dim.height/2-d.getSize().height/2);
        
        
    }//GEN-LAST:event_btn_deleteRecordActionPerformed

    private void btn_updateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateRecordActionPerformed
       
       //  this.setVisible(false);
        updateMember d=new updateMember();
     d.setVisible(true); 
    d.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    
    }//GEN-LAST:event_btn_updateRecordActionPerformed

    private void btn_searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchRecordActionPerformed
        
        // this.setVisible(false);
          searchMember d=new searchMember();
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_btn_searchRecordActionPerformed

    private void btn_addRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addRecordActionPerformed
      
        // this.setVisible(false);
     addMembers d=new addMembers();
    
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }//GEN-LAST:event_btn_addRecordActionPerformed

    private void btn_viewAllRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewAllRecordActionPerformed

      //     this.setVisible(false);
     showAllData d=new showAllData();
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_btn_viewAllRecordActionPerformed

    private void btn_viewAlloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewAlloActionPerformed
       
         reviewChurchDonations d=new reviewChurchDonations();
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }//GEN-LAST:event_btn_viewAlloActionPerformed

    private void btn_addoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addoActionPerformed
       
         add_Donation d=new add_Donation();
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_btn_addoActionPerformed

    private void btn_searchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchoActionPerformed
       
         search_Donations d=new search_Donations();
     d.setVisible(true);// TODO add your handling code here:
     d.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_btn_searchoActionPerformed

    private void btn_newRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newRegActionPerformed
       
         registerUser d=new registerUser();
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
           d.setLocation(dim.width/2-d.getSize().width/2, dim.height/2-d.getSize().height/2);
         d.setVisible(true);
        
    }//GEN-LAST:event_btn_newRegActionPerformed

    private void btn_removeRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeRegActionPerformed
     
         deleteUser d=new deleteUser();
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
           d.setLocation(dim.width/2-d.getSize().width/2, dim.height/2-d.getSize().height/2);
         d.setVisible(true);
        
    }//GEN-LAST:event_btn_removeRegActionPerformed

    private void btn_updateRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateRegActionPerformed
        
        
         updateUser d=new updateUser();
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
           d.setLocation(dim.width/2-d.getSize().width/2, dim.height/2-d.getSize().height/2);
         d.setVisible(true);
        
        
    }//GEN-LAST:event_btn_updateRegActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btn_viewAllRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewAllRegActionPerformed

        
       // login log = new login();
        
        
       
         
           loginViewUser d=new loginViewUser();        
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
           d.setLocation(dim.width/2-d.getSize().width/2, dim.height/2-d.getSize().height/2);
         d.setVisible(true);
    }//GEN-LAST:event_btn_viewAllRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Matel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainPage mp = new MainPage();
                mp.setSize(900,680); // Watever size you want to set
               //  Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
               //  mp.setLocation(dim.width/2-mp.getSize().width/2, dim.height/2-mp.getSize().height/2);
      //   mp.setExtendedState(mp.getExtendedState() | JFrame.MAXIMIZED_BOTH);  
                mp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mp.setVisible(true);
                databaseConnect dbCon = new databaseConnect();
                boolean conn = dbCon.isConnected();
                if(conn)
                {
                    
                    JOptionPane.showMessageDialog(mp, "Database Connected");
                   
                }else{
                     JOptionPane.showMessageDialog(mp, "Database not Connected");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addRecord;
    private javax.swing.JButton btn_addo;
    private javax.swing.JButton btn_deleteRecord;
    private javax.swing.JButton btn_newReg;
    private javax.swing.JButton btn_removeReg;
    private javax.swing.JButton btn_searchRecord;
    private javax.swing.JButton btn_searcho;
    private javax.swing.JButton btn_updateRecord;
    private javax.swing.JButton btn_updateReg;
    private javax.swing.JButton btn_viewAllRecord;
    private javax.swing.JButton btn_viewAllReg;
    private javax.swing.JButton btn_viewAllo;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
